# Generated by Django 5.0.1 on 2026-03-24 19:02

from django.db import migrations


def grant_admin_permissions(apps, schema_editor):
    """Grant admin permissions to qonqona@gmail.com"""
    User = apps.get_model('accounts', 'User')
    try:
        user = User.objects.get(email='qonqona@gmail.com')
        user.is_staff = True
        user.is_superuser = True
        user.user_type = 'admin'
        user.save()
        print(f"✓ Admin permissions granted to {user.email}")
    except User.DoesNotExist:
        print("⚠ User qonqona@gmail.com not found")


def reverse_admin_permissions(apps, schema_editor):
    """Reverse the admin permissions"""
    User = apps.get_model('accounts', 'User')
    try:
        user = User.objects.get(email='qonqona@gmail.com')
        user.is_staff = False
        user.is_superuser = False
        user.user_type = 'customer'
        user.save()
        print(f"✓ Admin permissions removed from {user.email}")
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(grant_admin_permissions, reverse_admin_permissions),
    ]
