# Generated by Django 5.0.1 on 2026-03-25 05:31

from django.db import migrations
from django.contrib.auth.hashers import make_password


def set_admin_password(apps, schema_editor):
    """Set password for qonqona@gmail.com"""
    User = apps.get_model('accounts', 'User')
    try:
        user = User.objects.get(email='qonqona@gmail.com')
        # Set password to: ElledenHotel@2026
        password = 'ElledenHotel@2026'
        user.password = make_password(password)
        user.save()
        print(f"✓ Password set for {user.email}")
        print(f"Password: {password}")
    except User.DoesNotExist:
        print("⚠ User qonqona@gmail.com not found")


def reverse_password(apps, schema_editor):
    """This migration cannot be safely reversed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grant_qonqona_admin'),
    ]

    operations = [
        migrations.RunPython(set_admin_password, reverse_password),
    ]
