# Generated by Django 5.0.1 on 2026-03-25 05:58

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_ibnuhassan_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    try:
        user, created = User.objects.get_or_create(
            email='ibnuhassan@gmail.com',
            defaults={
                'password': make_password('Adan7064.'),
                'is_staff': True,
                'is_superuser': True,
                'is_active': True,
                'user_type': 'admin',
                'first_name': 'Ibrahim',
                'last_name': 'Hassan',
            }
        )
        if created:
            print("✓ Superuser created: ibnuhassan@gmail.com")
        else:
            print("✓ Superuser already exists: ibnuhassan@gmail.com")
    except Exception as e:
        print(f"✗ Error creating superuser: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_admin_password'),
    ]

    operations = [
        migrations.RunPython(create_ibnuhassan_superuser),
    ]
