# Generated by Django 5.0.1 on 2026-03-25 06:20

from django.db import migrations
from django.contrib.auth.hashers import make_password


def update_ibnuhassan_password(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    try:
        user = User.objects.get(email='ibnuhassan@gmail.com')
        user.password = make_password('Adan7064.')
        user.save()
        print("✓ Password updated for ibnuhassan@gmail.com")
    except User.DoesNotExist:
        print("✗ User ibnuhassan@gmail.com not found")
    except Exception as e:
        print(f"✗ Error updating password: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_ibnuhassan_superuser'),
    ]

    operations = [
        migrations.RunPython(update_ibnuhassan_password),
    ]
