# Generated by Django 5.2.8 on 2026-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate Event'), ('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('government', 'Government/NGO Function'), ('religious', 'Religious Gathering'), ('family', 'Family Occasion'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue_address', models.TextField(help_text='Event venue/location')),
                ('guest_count', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('buffet', 'Buffet Service'), ('plated', 'Plated Service'), ('cocktail', 'Cocktail/Finger Food'), ('full_service', 'Full Service (Staff included)')], max_length=50)),
                ('menu_preferences', models.TextField(blank=True, help_text='Any specific menu items or dietary requirements')),
                ('budget_range', models.CharField(blank=True, help_text='Approximate budget', max_length=100)),
                ('additional_services', models.TextField(blank=True, help_text='Decorations, equipment, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quote Sent'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catering Inquiry',
                'verbose_name_plural': 'Catering Inquiries',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('meeting', 'Corporate Meeting'), ('training', 'Training/Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('wedding', 'Wedding/Reception'), ('product_launch', 'Product Launch'), ('government', 'Government Session'), ('ngo', 'NGO Workshop'), ('private', 'Private Celebration'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='For multi-day events', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendees', models.PositiveIntegerField()),
                ('package', models.CharField(choices=[('half_day', 'Half Day (4 Hours)'), ('full_day', 'Full Day (8 Hours)'), ('residential', 'Residential (Multi-day)'), ('custom', 'Custom Package')], max_length=20)),
                ('seating_arrangement', models.CharField(choices=[('u_shape', 'U-Shape'), ('classroom', 'Classroom'), ('banquet', 'Banquet'), ('theatre', 'Theatre'), ('boardroom', 'Boardroom')], max_length=20)),
                ('catering_required', models.BooleanField(default=True)),
                ('av_equipment_required', models.BooleanField(default=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conference Booking',
                'verbose_name_plural': 'Conference Bookings',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('room_booking', 'Room Booking'), ('restaurant', 'Restaurant Reservation'), ('conference', 'Conference Booking'), ('catering', 'Catering Inquiry'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast (6:00 AM - 10:00 AM)'), ('lunch', 'Lunch (12:00 PM - 3:00 PM)'), ('dinner', 'Dinner (6:00 PM - 10:00 PM)')], max_length=20)),
                ('time', models.TimeField(help_text='Preferred arrival time')),
                ('guests', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Reservation',
                'verbose_name_plural': 'Restaurant Reservations',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
