# Generated by Django 5.2.8 on 2026-03-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_guests', models.PositiveIntegerField(default=20)),
                ('menu_items', models.TextField(help_text='List of included items')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catering Package',
                'verbose_name_plural': 'Catering Packages',
                'ordering': ['price_per_person'],
            },
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='booking_reference',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='catering_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='equipment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantreservation',
            name='booking_reference',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='conferencebooking',
            name='package',
            field=models.CharField(choices=[('half_day', 'Half Day (4 Hours) - KES 15,000'), ('full_day', 'Full Day (8 Hours) - KES 25,000'), ('residential', 'Residential Package - KES 5,000/person'), ('custom', 'Custom Package')], max_length=20),
        ),
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default='', editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate Event'), ('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('government', 'Government/NGO Function'), ('religious', 'Religious Gathering'), ('family', 'Family Occasion'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue_address', models.TextField(help_text='Event venue/location')),
                ('guest_count', models.PositiveIntegerField()),
                ('custom_menu', models.TextField(blank=True, help_text='Custom menu items if not using package')),
                ('special_requests', models.TextField(blank=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.cateringpackage')),
            ],
            options={
                'verbose_name': 'Catering Order',
                'verbose_name_plural': 'Catering Orders',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('conference', 'Conference Booking'), ('catering', 'Catering Order')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catering_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='pages.cateringorder')),
                ('conference_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='pages.conferencebooking')),
            ],
            options={
                'verbose_name': 'Service M-Pesa Transaction',
                'verbose_name_plural': 'Service M-Pesa Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('conference', 'Conference Booking'), ('catering', 'Catering Order')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catering_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pages.cateringorder')),
                ('conference_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pages.conferencebooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
